include: .ci_base.yml

# base for merge requests that affect the core/tests
.testbeforemerge:
  only:
    refs:
      - merge_requests
    changes:
      - frackit/*
      - python/*
      - test/*

# using OpenCascade 7.3
ubuntu18.04 gcc-6 occ7.3:
  extends:
    - .ubuntu18.04 gcc-6
    - .testbeforemerge
  image: git.iws.uni-stuttgart.de:4567/tools/frackit/ubuntu18.04_occ7.3:latest

ubuntu18.04 gcc-7 occ7.3:
  extends:
    - .ubuntu18.04 gcc-6
    - .testbeforemerge
  image: git.iws.uni-stuttgart.de:4567/tools/frackit/ubuntu18.04_occ7.3:latest

ubuntu18.04 gcc-8 occ7.3:
  extends:
    - .ubuntu18.04 gcc-8
    - .testbeforemerge
  image: git.iws.uni-stuttgart.de:4567/tools/frackit/ubuntu18.04_occ7.3:latest
